name: Protobufs

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate_protobufs:
    name: Validate Protobufs
    runs-on: ubuntu-latest
    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ github.job }}-${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
    - name: Install protobuf
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Lint protobufs
      run: |
        go install github.com/googleapis/api-linter/cmd/api-linter@latest
        make protoimports
        cd protobuf-import
        find github.com/openconfig/featureprofiles/ -name \*.proto -exec api-linter --disable-rule all --enable-rule core {} \+
    - name: Validate textprotos
      run: |
        go install github.com/bstoll/textproto-validator@latest
        make protoimports
        for i in `find . -name \*.textproto`; do
          textproto-validator -I ./protobuf-import $i
        done
